"""Add WhatsAppSession model

Revision ID: a6f6f53d7c77
Revises: 0001
Create Date: 2026-09-01 15:09:34.924649
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6f6f53d7c77'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_sessions',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_index(op.f('ix_audit_log_centre_id'), 'audit_log', ['centre_id'], unique=False)
    op.drop_constraint('officers_employee_id_key', 'officers', type_='unique')
    op.drop_index('ix_officers_employee_id', table_name='officers')
    op.create_index(op.f('ix_officers_employee_id'), 'officers', ['employee_id'], unique=True)
    op.drop_constraint('payment_status_procurement_record_id_key', 'payment_status', type_='unique')
    op.create_index(op.f('ix_payment_status_procurement_record_id'), 'payment_status', ['procurement_record_id'], unique=True)
    op.drop_constraint('procurement_records_queue_entry_id_key', 'procurement_records', type_='unique')
    op.drop_index('ix_procurement_records_queue_entry_id', table_name='procurement_records')
    op.create_index(op.f('ix_procurement_records_queue_entry_id'), 'procurement_records', ['queue_entry_id'], unique=True)
    op.drop_constraint('qr_tokens_queue_entry_id_key', 'qr_tokens', type_='unique')
    op.drop_index('ix_qr_tokens_queue_entry_id', table_name='qr_tokens')
    op.create_index(op.f('ix_qr_tokens_queue_entry_id'), 'qr_tokens', ['queue_entry_id'], unique=True)
    op.drop_index('uq_queue_entries_active_farmer_centre', table_name='queue_entries', postgresql_where="((status)::text = ANY ((ARRAY['WAITING'::character varying, 'CHECKED_IN'::character varying, 'PROCESSING'::character varying])::text[]))")
    op.create_index(op.f('ix_queue_entries_centre_id'), 'queue_entries', ['centre_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_farmer_user_id'), 'queue_entries', ['farmer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_entries_farmer_user_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_centre_id'), table_name='queue_entries')
    op.create_index('uq_queue_entries_active_farmer_centre', 'queue_entries', ['centre_id', 'farmer_user_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['WAITING'::character varying, 'CHECKED_IN'::character varying, 'PROCESSING'::character varying])::text[]))")
    op.drop_index(op.f('ix_qr_tokens_queue_entry_id'), table_name='qr_tokens')
    op.create_index('ix_qr_tokens_queue_entry_id', 'qr_tokens', ['queue_entry_id'], unique=False)
    op.create_unique_constraint('qr_tokens_queue_entry_id_key', 'qr_tokens', ['queue_entry_id'])
    op.drop_index(op.f('ix_procurement_records_queue_entry_id'), table_name='procurement_records')
    op.create_index('ix_procurement_records_queue_entry_id', 'procurement_records', ['queue_entry_id'], unique=False)
    op.create_unique_constraint('procurement_records_queue_entry_id_key', 'procurement_records', ['queue_entry_id'])
    op.drop_index(op.f('ix_payment_status_procurement_record_id'), table_name='payment_status')
    op.create_unique_constraint('payment_status_procurement_record_id_key', 'payment_status', ['procurement_record_id'])
    op.drop_index(op.f('ix_officers_employee_id'), table_name='officers')
    op.create_index('ix_officers_employee_id', 'officers', ['employee_id'], unique=False)
    op.create_unique_constraint('officers_employee_id_key', 'officers', ['employee_id'])
    op.drop_index(op.f('ix_audit_log_centre_id'), table_name='audit_log')
    op.drop_table('whatsapp_sessions')
    # ### end Alembic commands ###
